### ISSUE TITLE
can‘t find faiss/c_api/IndexFlat_c.h

### ISSUE THREAD

**Issue by XuKyle** [DataIntelligenceCrew/go-faiss#1]
after build ，don't have _c.h file

-- Up-to-date: /usr/local/include/faiss/IVFlib.h

# github.com/DataIntelligenceCrew/go-faiss
/root/go_projects/src/github.com/DataIntelligenceCrew/go-faiss/faiss.go:11:37: fatal error: faiss/c_api/IndexFlat_c.h: No such file or directory
 #include <faiss/c_api/IndexFlat_c.h>
                                     ^
compilation terminated.

please help me。

**Comment by XuKyle** [comment]
when i copy c_api to /usr/local/include/faiss ,seem it find the file.but another error happen ..


/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libfaiss_c.so: undefined reference to `faiss::IndexFlatL2BaseShift::IndexFlatL2BaseShift(long, unsigned long, float const*)'
collect2: error: ld returned 1 exit status

**Comment by pauloue** [comment]
Did you follow the instructions for building Faiss in the README and use https://github.com/DataIntelligenceCrew/faiss/tree/C-api-cmake? Upstream Faiss removed IndexL2BaseShift in commit https://github.com/facebookresearch/faiss/commit/e1adde0d84ece584f3b4d86db0b1532329f8cdb8 but it was left in this file: https://github.com/facebookresearch/faiss/blob/master/c_api/IndexFlat_c.cpp. Maybe your build included that commit?

**Comment by XuKyle** [comment]
> Did you follow the instructions for building Faiss in the README and use https://github.com/DataIntelligenceCrew/faiss/tree/C-api-cmake? Upstream Faiss removed IndexL2BaseShift in commit [facebookresearch/faiss@e1adde0](https://github.com/facebookresearch/faiss/commit/e1adde0d84ece584f3b4d86db0b1532329f8cdb8) but it was left in this file: https://github.com/facebookresearch/faiss/blob/master/c_api/IndexFlat_c.cpp. Maybe your build included that commit?

thank you . i try again and it works 。
