### ISSUE TITLE
Error in operation example: regex_error 

### ISSUE THREAD

**Issue by Forget-C** [DataIntelligenceCrew/go-faiss#10]
I use faiss version 1.7.1, Error in operation example: regex_error 。
I tried to reduce the version, but the project didn't work。
I'm using version 1ea134eb83778310452111452b60f14391f92ad6 of faiss now，It's generally normal，However, idmap is invalid, and add_WITH_IDS cannot be used： “Error in virtual void faiss::Index::add_with_ids(faiss::Index::idx_t, const float*, const idx_t*) at /opt/faiss/faiss/Index.cpp:39: add_with_ids not implemented for this type of index”

**Comment by p-ouellette** [comment]
All the examples in _example are working for me with the latest faiss.
Not all indexes support AddWithIDs. To use it with a flat index you need an IDMap. The index factory string would be "IDMap,Flat".

**Comment by Forget-C** [comment]
Thank you for your reply。
the "add_with_ids" problem has been fixed，It's my own bug。
teh “regex_error” problem Still exist， I'm not sure if it's related to my operating environment。 （faiss version 1.7.1）
system: CentOS Linux release 7.7.1908
c++: 4.8.5
cmake: 3.21.0

**Comment by p-ouellette** [comment]
When do you get the error? Is it a compile error or runtime error? Can you post the code that causes it?

**Comment by Forget-C** [comment]
ok
I use the sample code from the project。
flat.go, Can run
```
[root@b160014f5b05 _example]# go run flat/flat.go
IsTrained() = true
Ntotal() = 100000
ids=
    0   427    93   497
    1   227  1097   411
    2   126   513   493
    3   177   227   357
    4    28   198    10
dist=
      0 5.93397 6.23689 6.35722
      0 5.80749 6.24904 6.82128
      0 5.98183 6.21018 6.34563
      0 8.10436 8.11447 8.27493
      0 7.12338 7.55592 7.61045
ids (first 5 results)=
   82   476   677   165
  503   145   230   238
  785   201  1209  1320
 1010   930  1273   208
  296   929   241   742
ids (last 5 results)=
 9330  9238  9619  9052
 9839 10393 10064 10293
 9809 10819 10623  9392
11030 10383 11252 10668
10453  9318 10392  8658
```
ivfflat.go,ivfpq.go. Cannot run. No code has been changed
```
[root@b160014f5b05 _example]# go run ivfflat/ivfflat.go
regex_error
2021/07/26 01:39:37 std::exception
exit status 1
[root@b160014f5b05 _example]# go run ivfpq/ivfpq.go
regex_error
2021/07/26 01:40:38 std::exception
exit status 1
```

**Comment by p-ouellette** [comment]
I'm guessing it's an issue with faiss. The error is probably coming from https://github.com/facebookresearch/faiss/blob/master/faiss/index_factory.cpp#L255. You could try using index_factory in C++ and see if you get the same error. Try running https://github.com/facebookresearch/faiss/blob/master/tutorial/cpp/2-IVFFlat.cpp but change it to use index_factory: 
`faiss::Index *index = faiss::index_factory(d, "IVF100,Flat");`.

**Comment by Forget-C** [comment]
ok thanks, I'll try

**Comment by sodowe666** [comment]
> ok thanks, I'll try

hi bro . did you fix this problem. i meet this too.

**Comment by p-ouellette** [comment]
>  c++: 4.8.5

I'm pretty sure that's the problem. GCC 4.8 does not support `std::regex`. You need to upgrade your compiler.

**Comment by p-ouellette** [comment]
See https://github.com/facebookresearch/faiss/issues/2053
