### ISSUE TITLE
make -C build  Linking CXX executable faiss_test error

### ISSUE THREAD

**Issue by caidongsen** [DataIntelligenceCrew/go-faiss#11]
Hello, I encountered the following problems, I do not know how to solve, could you help me to take a look？

[ 96%] Building CXX object tests/CMakeFiles/faiss_test.dir/test_pq_encoding.cpp.o
[ 96%] Building CXX object tests/CMakeFiles/faiss_test.dir/test_sliding_ivf.cpp.o
[ 98%] Building CXX object tests/CMakeFiles/faiss_test.dir/test_threaded_index.cpp.o
[ 98%] Building CXX object tests/CMakeFiles/faiss_test.dir/test_transfer_invlists.cpp.o
[100%] Linking CXX executable faiss_test
/mnt/c/GOPATH/src/github.com/facebookresearch/faiss/build/tests/faiss_test: symbol lookup error: /mnt/c/GOPATH/src/github.com/facebookresearch/faiss/build/tests/faiss_test: undefined symbol: _ZNK5faiss5Index6assignElPKfPll
CMake Error at /usr/share/cmake/Modules/GoogleTestAddTests.cmake:77 (message):
  Error running test executable.

    Path: '/mnt/c/GOPATH/src/github.com/facebookresearch/faiss/build/tests/faiss_test'
    Result: 127
    Output:

Call Stack (most recent call first):
  /usr/share/cmake/Modules/GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl)

make[2]: *** [tests/CMakeFiles/faiss_test.dir/build.make:311: tests/faiss_test] Error 1
make[2]: *** Deleting file 'tests/faiss_test'
make[2]: Leaving directory '/mnt/c/GOPATH/src/github.com/facebookresearch/faiss/build'
make[1]: *** [CMakeFiles/Makefile2:1520: tests/CMakeFiles/faiss_test.dir/all] Error 2
make[1]: Leaving directory '/mnt/c/GOPATH/src/github.com/facebookresearch/faiss/build'
make: *** [Makefile:146: all] Error 2
make: Leaving directory '/mnt/c/GOPATH/src/github.com/facebookresearch/faiss/build'

**Comment by caidongsen** [comment]
I ignored the error,and I go run falt.go,then I meet this:
# github.com/DataIntelligenceCrew/go-faiss
/usr/bin/ld: $WORK/b032/_x002.o: in function `_cgo_66e7c26abcb0_Cfunc_faiss_ParameterSpace_free':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `faiss_ParameterSpace_free'
collect2: error: ld returned 1 exit status

**Comment by p-ouellette** [comment]
Make sure libfaiss_c.so is installed in a place where the linker will find it like /usr/lib. You might need to run `sudo ldconfig` after installing it (on Linux). You could also use the `CGO_LDFLAGS` environment variable to set the linker flags if the lib is not installed system-wide.
