### ISSUE TITLE
Linking CXX shared library libfaiss_python_callbacks.dylib。Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by sodowe666** [DataIntelligenceCrew/go-faiss#12]
[ 61%] Linking CXX shared library libfaiss_python_callbacks.dylib
Undefined symbols for architecture arm64:
  "_PyBytes_AsString", referenced from:
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "_PyBytes_FromStringAndSize", referenced from:
      PyCallbackIOWriter::operator()(void const*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "_PyBytes_Size", referenced from:
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "_PyGILState_Ensure", referenced from:
      (anonymous namespace)::PyThreadLock::PyThreadLock() in python_callbacks.cpp.o
  "_PyGILState_Release", referenced from:
      (anonymous namespace)::PyThreadLock::~PyThreadLock() in python_callbacks.cpp.o
  "_PyObject_CallFunction", referenced from:
      PyCallbackIOWriter::operator()(void const*, unsigned long, unsigned long) in python_callbacks.cpp.o
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "__Py_Dealloc", referenced from:
      _Py_DECREF(_object*) in python_callbacks.cpp.o
  "faiss::FaissException::FaissException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, char const*, int)", referenced from:
      PyCallbackIOWriter::operator()(void const*, unsigned long, unsigned long) in python_callbacks.cpp.o
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "faiss::IOReader::fileno()", referenced from:
      vtable for PyCallbackIOReader in python_callbacks.cpp.o
  "faiss::IOWriter::fileno()", referenced from:
      vtable for PyCallbackIOWriter in python_callbacks.cpp.o
  "typeinfo for faiss::FaissException", referenced from:
      PyCallbackIOWriter::operator()(void const*, unsigned long, unsigned long) in python_callbacks.cpp.o
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "typeinfo for faiss::IOReader", referenced from:
      typeinfo for PyCallbackIOReader in python_callbacks.cpp.o
  "typeinfo for faiss::IOWriter", referenced from:
      typeinfo for PyCallbackIOWriter in python_callbacks.cpp.o
  "vtable for faiss::FaissException", referenced from:
      faiss::FaissException::~FaissException() in python_callbacks.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for faiss::IOReader", referenced from:
      faiss::IOReader::IOReader() in python_callbacks.cpp.o
      faiss::IOReader::~IOReader() in python_callbacks.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for faiss::IOWriter", referenced from:
      faiss::IOWriter::IOWriter() in python_callbacks.cpp.o
      faiss::IOWriter::~IOWriter() in python_callbacks.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [faiss/python/libfaiss_python_callbacks.dylib] Error 1
make[1]: *** [faiss/python/CMakeFiles/faiss_python_callbacks.dir/all] Error 2
make: *** [all] Error 2

Did anyone meet this problem? need some help. where is libfaiss_python_callbacks.dylib from. how should I fix it.

**Comment by sodowe666** [comment]
it happen at my macbookPro M1。anybody know this problem?

**Comment by p-ouellette** [comment]
Try disabling the python bindings with the cmake option `-DFAISS_ENABLE_PYTHON=OFF`.

**Comment by sodowe666** [comment]
> Try disabling the python bindings with the cmake option `-DFAISS_ENABLE_PYTHON=OFF`.

It pass. thank you.
