### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by sodowe666** [DataIntelligenceCrew/go-faiss#13]
# github.com/DataIntelligenceCrew/go-faiss
ld: warning: ignoring file /usr/local/lib/libfaiss_c.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_faiss_IDSelectorBatch_new", referenced from:
      __cgo_b3ad317e889f_Cfunc_faiss_IDSelectorBatch_new in _x007.o
     (maybe you meant: __cgo_b3ad317e889f_Cfunc_faiss_IDSelectorBatch_new)
  "_faiss_IDSelectorRange_new", referenced from:
。。。。。

it happen at macbook M1 when I go build。  how should I cmake faiss for macOS-arm64 ,aka macbook M1

**Comment by p-ouellette** [comment]
It looks like the faiss lib is built for arm64 but go is trying to build for x86_64.
What does `go version` say?
