### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by sodowe666** [DataIntelligenceCrew/go-faiss#14]
：../../../../../../../../github.com/DataIntelligenceCrew/go-faiss/autotune.go:5:36: error: faiss/c_api/AutoTune_c.h: No such file or directory

anyone meet this problem? please help.

i already mv /faiss/build/c_api/libfaiss_c.so to /usr/lib/libfaiss_c.so and /usr/local/lib/libfaiss_c.so

but when i go build my go program . error occur.

**Comment by p-ouellette** [comment]
Did you install the header files as well? They should be installed when you install faiss with `make install`.
If the headers aren't being found you can tell cgo where they are with e.g. `export CGO_CFLAGS="-I /usr/local/include"` or wherever you installed them.

**Comment by sodowe666** [comment]
> 

I dont know ... i just know it generate libfaiss_c.so file  . and I move it to /usr/bin and /usr/local/bin . how should I know that I have installed the header file when Installing faiss.

**Comment by sodowe666** [comment]
> Did you install the header files as well? They should be installed when you install faiss with `make install`. If the headers aren't being found you can tell cgo where they are with e.g. `export CGO_CFLAGS="-I /usr/local/include"` or wherever you installed them.


I dont know ... i just know it generate libfaiss_c.so file . and I move it to /usr/bin and /usr/local/bin . how should I know that I have installed the header file when Installing faiss.

**Comment by p-ouellette** [comment]
The header files should be installed if you installed faiss with `sudo make -C build install`.
By default I think they will be installed to `/usr/local/include/faiss` unless you specified a different location.
If they are installed there but it's still not working, try using the `CGO_CFLAGS` variable.

**Comment by sodowe666** [comment]
> The header files should be installed if you installed faiss with `sudo make -C build install`. By default I think they will be installed to `/usr/local/include/faiss` unless you specified a different location. If they are installed there but it's still not working, try using the `CGO_CFLAGS` variable.

perhaps it`s my env problem . i am not doing this at my local PC. thanks bro .

**Comment by sodowe666** [comment]
> The header files should be installed if you installed faiss with `sudo make -C build install`. By default I think they will be installed to `/usr/local/include/faiss` unless you specified a different location. If they are installed there but it's still not working, try using the `CGO_CFLAGS` variable.

that means I need all file of `/usr/local/include/faiss ` and /usr/local/lib/libfaiss_c.so? now
