### ISSUE TITLE
cgo: inconsistent definitions for C.FaissMetricType

### ISSUE THREAD

**Issue by sodowe666** [DataIntelligenceCrew/go-faiss#15]
when I go get github.com/DataIntelligenceCrew/go-faiss . it occur. 
cgo: inconsistent definitions for C.FaissMetricType.

and I have move libfaiss_c.so to /usr/lib

anyone meet this problem?

**Comment by sodowe666** [comment]
> when I go get github.com/DataIntelligenceCrew/go-faiss . it occur. cgo: inconsistent definitions for C.FaissMetricType.
> 
> and I have move libfaiss_c.so to /usr/lib
> 
> anyone meet this problem?

is it faiss`s version problem? or goland`s version problem?

**Comment by p-ouellette** [comment]
Probably a go version. Try updating to the latest version.

**Comment by sodowe666** [comment]
> ?

it`s go 1.16.9. need to update to 1.18?

**Comment by sodowe666** [comment]
> Probably a go version. Try updating to the latest version.

it`s go 1.16.9. need to update to 1.18?

**Comment by sodowe666** [comment]
> Probably a go version. Try updating to the latest version.

But company`s release version is go1.16.13

**Comment by sodowe666** [comment]
it `s not go version problem. it could pass at my local PC. but not Remote server.

**Comment by sodowe666** [comment]
> Probably a go version. Try updating to the latest version.

I know why now.
damn it . it redeclare FaissMetricType enum in IndexFlat_c.h and IndexFlat_c.h
you could search `typedef enum FaissMetricType FaissMetricType` at /usr/local/include/faiss/c_api/IndexFlat_c.h(IndexFlat_c.h)
commented it out. will fix this problem.
