### ISSUE TITLE
regex_error , std::exception

### ISSUE THREAD

**Issue by sodowe666** [DataIntelligenceCrew/go-faiss#17]
when I call `faiss.IndexFactory` it occur. can anybody help? i dont know what the problem it is.

**Comment by sodowe666** [comment]
what is different between faiss.IndexFactory and faiss.NewIndexFlat?
this error occur when I use faiss.IndexFactory. but It pass when I use faiss.NewIndexFlat.

**Comment by sodowe666** [comment]
by the way , it`s centos system

**Comment by p-ouellette** [comment]
IndexFactory uses a regular expression to parse the string that specifies the index.
What version of GCC are you using? If it's very old, then it might not support the regex library used.
Do you get the same error with the C++ version? If you do, then it's a faiss problem.

**Comment by p-ouellette** [comment]
Your GCC is too old, see https://github.com/facebookresearch/faiss/issues/2053

**Comment by sodowe666** [comment]
> IndexFactory uses a regular expression to parse the string that specifies the index. What version of GCC are you using? If it's very old, then it might not support the regex library used. Do you get the same error with the C++ version? If you do, then it's a faiss problem.

i fix it now . it is gcc `s version problem  .i upgrade gcc to gcc9. it is ok now .
