### ISSUE TITLE
type uint32 in assignment

### ISSUE THREAD

**Issue by XuKyle** [DataIntelligenceCrew/go-faiss#2]
after compile on 
CentOS Linux release 7.9.2009 (Core)
x86_64

i got this :

# github.com/DataIntelligenceCrew/go-faiss
/root/go/src/github.com/DataIntelligenceCrew/go-faiss/faiss.go:317:62: cannot use _Ctype_FaissMetricType(metric) (type _Ctype_FaissMetricType) as type uint32 in assignment
/root/go/src/github.com/DataIntelligenceCrew/go-faiss/faiss.go:338:81: cannot use _Ctype_FaissMetricType(metric) (type _Ctype_FaissMetricType) as type uint32 in assignment

**Comment by pauloue** [comment]
I can't reproduce. You could try using the latest version of go if you aren't already.

**Comment by XuKyle** [comment]
> I can't reproduce. You could try using the latest version of go if you aren't already.

thank you.
i fixed 。

I used go1.15 before ， and  above happen。

now I use go version go1.14.2 linux/amd64。

**Comment by xusk** [comment]
> > I can't reproduce. You could try using the latest version of go if you aren't already.
> 
> thank you.
> i fixed 。
> 
> I used go1.15 before ， and above happen。
> 
> now I use go version go1.14.2 linux/amd64。

with the go version go1.14.2 

cgo: inconsistent definitions for C.FaissMetricType

**Comment by xusk** [comment]
yum install centos-release-scl
yum-config-manager --enable rhel-server-rhscl-7-rpms
yum install devtoolset-7
scl enable devtoolset-7 bash
