### ISSUE TITLE
help: Can help to achieve the  FaissIndexIVFFlat

### ISSUE THREAD

**Issue by XuKyle** [DataIntelligenceCrew/go-faiss#3]
i tried,but i don't know c++ well.
can you add the  FaissIndexIVFFlat。
thanks

**Comment by pauloue** [comment]
You can create the index with the IndexFactory. The description string would be e.g. "IVF4096,Flat". See https://github.com/facebookresearch/faiss/wiki/Faiss-indexes and https://github.com/facebookresearch/faiss/wiki/The-index-factory.

**Comment by pauloue** [comment]
I added an example for IndexIVFFlat: https://github.com/DataIntelligenceCrew/go-faiss/blob/master/_example/ivfflat/ivfflat.go.
