### ISSUE TITLE
Not compilable in Mac OS

### ISSUE THREAD

**Issue by XuChen-Repair** [DataIntelligenceCrew/go-faiss#5]
Hi, the setup commands in the wiki works fine with me in Ubuntu OS, but i got some error when setup on Mac. Just want to check if it can be compiled on Mac?

> make -C build
[ 61%] Built target faiss
[ 62%] Built target swigfaiss_swig_compilation
[ 62%] Linking CXX shared library libfaiss_python_callbacks.dylib
Undefined symbols for architecture x86_64:
  "_PyBytes_AsString", referenced from:
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "_PyBytes_FromStringAndSize", referenced from:
      PyCallbackIOWriter::operator()(void const*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "_PyBytes_Size", referenced from:
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "_PyGILState_Ensure", referenced from:
      (anonymous namespace)::PyThreadLock::PyThreadLock() in python_callbacks.cpp.o
  "_PyGILState_Release", referenced from:
      (anonymous namespace)::PyThreadLock::~PyThreadLock() in python_callbacks.cpp.o
  "_PyObject_CallFunction", referenced from:
      PyCallbackIOWriter::operator()(void const*, unsigned long, unsigned long) in python_callbacks.cpp.o
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "faiss::FaissException::FaissException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, char const*, int)", referenced from:
      PyCallbackIOWriter::operator()(void const*, unsigned long, unsigned long) in python_callbacks.cpp.o
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "faiss::IOReader::fileno()", referenced from:
      vtable for PyCallbackIOReader in python_callbacks.cpp.o
  "faiss::IOWriter::fileno()", referenced from:
      vtable for PyCallbackIOWriter in python_callbacks.cpp.o
  "typeinfo for faiss::FaissException", referenced from:
      PyCallbackIOWriter::operator()(void const*, unsigned long, unsigned long) in python_callbacks.cpp.o
      PyCallbackIOReader::operator()(void*, unsigned long, unsigned long) in python_callbacks.cpp.o
  "typeinfo for faiss::IOReader", referenced from:
      typeinfo for PyCallbackIOReader in python_callbacks.cpp.o
  "typeinfo for faiss::IOWriter", referenced from:
      typeinfo for PyCallbackIOWriter in python_callbacks.cpp.o
  "vtable for faiss::FaissException", referenced from:
      faiss::FaissException::~FaissException() in python_callbacks.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for faiss::IOReader", referenced from:
      faiss::IOReader::IOReader() in python_callbacks.cpp.o
      faiss::IOReader::~IOReader() in python_callbacks.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for faiss::IOWriter", referenced from:
      faiss::IOWriter::IOWriter() in python_callbacks.cpp.o
      faiss::IOWriter::~IOWriter() in python_callbacks.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [faiss/python/libfaiss_python_callbacks.dylib] Error 1
make[1]: *** [faiss/python/CMakeFiles/faiss_python_callbacks.dir/all] Error 2
make: *** [all] Error 2

**Comment by p-ouellette** [comment]
It looks like you're missing the python libraries. You could try compiling with `-DFAISS_ENABLE_PYTHON=OFF`.

**Comment by XuChen-Repair** [comment]
It works! Thank you.
